# Server Configuration
spring.application.name=order-service
server.port=8082

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=Harshini@258
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ActiveMQ Configuration
spring.activemq.broker-url=tcp://localhost:62626
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.pub-sub-domain=false

# Event Publisher Configuration
event.publisher.enabled=true
event.publisher.polling.interval=5000
event.publisher.polling.batch-size=10
event.publisher.max-retry-count=3
event.publisher.database-type=JDBC
event.publisher.queue-mapping.OrderCreated=order-to-notification-queue
