server.port=8081
spring.application.name=inventory-service

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/inventory_db

# ActiveMQ
spring.activemq.broker-url=tcp://localhost:62626

# Event Publisher - MongoDB
event.publisher.database-type=MONGODB
event.publisher.outbox-table=outbox_events
event.publisher.status-column=status
event.publisher.queue-mapping.InventoryUpdated=inventory-to-order-queue
